export const QUEUE_URL = process.env.QUEUE_URL;
export const DATABASE_URL = process.env.DATABASE_URL;
export const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;
export const PRIVATE_KEY = process.env.PRIVATE_KEY;
export const APIFY_API_KEY=process.env.APIFY_API;
export const COOKIE_SECRET=process.env.COOKIE_SECRET;
export const WEBHOOK_URL=process.env.WEBHOOK_URL;
export const ACTOR_URL=process.env.ACTOR_URL;
export const ML_MODEL_ENDPOINT=process.env.ML_MODEL_ENDPOINT;